In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\AYSHA NASARIN\OneDrive\day12_cleaned.csv")

In [4]:
df.shape

(9994, 9)

In [5]:
df.head()

,Order Date,Order ID,Customer ID,Postal Code,Sales,Quantity,Discount,Product ID,Profit
0,11-Aug-16,CA-2016-152156,CG-12520,42420,? 731.94,3,0.0,FUR-CH-10000454,? 219.582
1,25-Sep-15,CA-2015-106320,EB-13870,84057,"? 1,044.63",3,0.0,FUR-TA-10000577,? 240.2649
2,16-Jan-16,CA-2016-121755,EH-13945,90049,? 90.57,3,0.0,TEC-AC-10003027,? 11.7741
3,20-Jun-16,CA-2016-169194,LH-16900,19901,? 45.,3,0.0,TEC-AC-10002167,? 4.95
4,24-Nov-15,CA-2015-135545,KM-16720,90004,? 146.73,3,0.0,OFF-PA-10003892,? 68.9631

In [6]:
df.tail()

,Order Date,Order ID,Customer ID,Postal Code,Sales,Quantity,Discount,Product ID,Profit
9989,16-Feb-16,CA-2016-105781,JF-15565,10024,? 326.646,3,0.10,FUR-CH-10001802,? 39.9234
9990,27-Mar-17,CA-2017-144491,CJ-12010,77070,"? 1,023.332",5,0.32,FUR-BO-10001811,30.098 -?
9991,21-Aug-16,CA-2016-122581,JK-15370,10035,? 573.174,7,0.10,FUR-CH-10002961,? 63.686
9992,13-Nov-15,CA-2015-104948,KH-16510,92404,? 683.332,4,0.15,FUR-BO-10004357,40.196 -?
9993,19-Mar-15,CA-2015-168088,CM-12655,77041,? 383.4656,4,0.32,FUR-BO-10004218,67.6704 -?

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order Date   9994 non-null   object
 1   Order ID     9994 non-null   object
 2   Customer ID  9994 non-null   object
 3   Postal Code  9994 non-null   int64
 4   Sales        9994 non-null   object
 5   Quantity     9994 non-null   int64
 6   Discount     9994 non-null   float64
 7   Product ID   9994 non-null   object
 8   Profit       9994 non-null   object
dtypes: float64(1), int64(2), object(6)
memory usage: 702.8+ KB

In [8]:
df.describe()

        Postal Code     Quantity     Discount
count   9994.000000  9994.000000  9994.000000
mean   55190.379428     3.789574     0.156203
std    32063.693350     2.225110     0.206452
min     1040.000000     1.000000     0.000000
25%    23223.000000     2.000000     0.000000
50%    56430.500000     3.000000     0.200000
75%    90008.000000     5.000000     0.200000
max    99301.000000    14.000000     0.800000

In [10]:
#how many rows
df.shape[0]

9994

In [11]:
#how many columns
df.shape[1]

9

In [12]:
#which columns have missing values
df.isnull().sum()

Order Date     0
Order ID       0
Customer ID    0
Postal Code    0
Sales          0
Quantity       0
Discount       0
Product ID     0
Profit         0
dtype: int64

In [15]:
#what is the average value of one numeric column
a=df["Quantity"].mean().round(2)
print(a)

3.79